# SQLite Datasource
spring.application.name=sqlite
spring.datasource.url=jdbc:sqlite:jpa-example-database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Liquibase
spring.liquibase.enabled=true