application {
  name = "application.name"

  i18n-bundle-prefix = "i18n"

  user-management {
    enabled = true
    access-control = {
      roles = ["manager", "admin"]
    }
    registration = true
    additional-table-fields = [{name = "start_date", type = "date"}]
  }

  selects {
    task-status {
      open = "selects.task-status.open"
      todo = "selects.task-status.todo"
      work-in-progress = "selects.task-status.progress"
      closed = "selects.task-status.closed"
    }
  }

  versioning {
    enabled = true
    tables = ["projects", "tasks", "employees", "comments"]
  }

  auditing {
    enabled = true
    actions = ["create", "update", "delete", "login", "logout"]
  }

  tables = {
    "projects" = {
      fields = {
        id = {type = "id", primary = true},
        name = {type = "text", required = true, max-length = 255},
        description = {type = "text", max-length = 500},
        start_date = {type = "date"},
        end_date = {type = "date"},
        created_at = {type = "datetime"},
        updated_at = {type = "datetime"}
      }
    },
    "tasks" = {
      fields = {
        id = {type = "id", primary = true},
        title = {type = "text", required = true, max-length = 255},
        description = {type = "text", max-length = 1000},
        assigned_to = {type = "number"},
        status = {type = "select", values = "task-status"},
        due_date = {type = "date", read-only-for-roles = ["developer"]},
        created_at = {type = "datetime"},
        updated_at = {type = "datetime"}
      }
    },
    "comments" = {
      fields = {
        id = {type = "id", primary = true},
        comment_text = {type = "text", max-length = 1000},
        employee_id = {type = "number"},
        created_at = {type = "datetime", default = "now()"}
      }
    }
    #"images" = {
    #  id = {type = "id", primary = true},
    #  title = {type = "image", required = true},
    #}
  }
  routes = {
    "projects" = {
      default-route = true
      table = "projects"
      title = "route.projects.title"
      renderer = "item"
      render-configuration {
        inline-edit = true
        item-renderer = {
          type = "entity-item-card-renderer"
          title-field = "name"
          description-field = "description"
        }
        detail-renderer {
          title-field = "title"
          type = "form-detail-renderer", children = [
            {field = "title"},
            {field = "description"},
            {field = "status"},
            {field = "due_date"}
          ]
        }
        access-control = {
          roles = ["manager", "admin"]
        }
      }
    },
    "tasks" = {
      table = "tasks"
      title = "route.tasks.title"
      renderer = "master-detail"
      render-configuration = {
        item-renderer = {
          type = "entity-item-card-renderer"
          title-field = "name"
          description-field = "description"
        }
        detail-renderer {
          title-field = "title"
          type = "form-detail-renderer", children = [
            {field = "title"},
            {field = "description"},
            {field = "status"},
            {field = "due_date"}
            #{type = "relationship", read-only=true }
          ]
        }
      }
      access-control = {
        roles = ["developer", "manager", "admin"]
      }
    }
  }
}