package com.github.appreciated.turbo_crud.service;

import com.github.appreciated.turbo_crud.config.model.*;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * Service for loading and providing access to the Turbo CRUD configuration.
 * Reads configuration from a resource file and offers methods to retrieve route and application settings.
 */

@Service
public class TurboCrudConfigService {

    private final Application configuration;

    public TurboCrudConfigService() {

        configuration = Application.Builder.of()
                .withName("application.name")
                .withI18nBundlePrefix("some_i18n")
                .withUserManagement(UserManagement.Builder.of()
                        .withEnabled(true)
                        .withAccessControl(AccessControl.Builder.of().withRoles(List.of("manager", "admin")).build())
                        .withSignUp(true)
                        .withAdditionalFields(List.of(AdditionalField.Builder.of()
                                .withName("start_date")
                                .withType("date")
                                .build()))
                        .build())
                .withSelects(Selects.Builder.of()
                        .withConfigs(Map.of("task-status",
                                Map.of("open", "selects.task-status.open",
                                        "todo", "selects.task-status.todo",
                                        "work-in-progress", "selects.task-status.progress",
                                        "closed", "selects.task-status.closed")))
                        .build())
                .withVersioning(Versioning.Builder.of()
                        .withEnabled(true)
                        .withRepositories(List.of("projects", "tasks", "task_comments"))
                        .build())
                .withAuditing(Auditing.Builder.of()
                        .withEnabled(true)
                        .withActions(List.of("create", "update", "delete", "login", "logout"))
                        .build())
                .withRepositories(Map.of("projects", Repository.Builder.of()
                        .withFactory("jpa")
                        .withFields(Map.of("id", Field.Builder.of()
                                .withFactory("id")
                                .withPrimary(true)
                                .build(), "name", Field.Builder.of()
                                .withFactory("text")
                                .withRequired(true)
                                .withValidation(Validation.Builder.of().withMaxLength(255).build())
                                .build(), "description", Field.Builder.of()
                                .withFactory("textarea")
                                .withValidation(Validation.Builder.of().withMaxLength(500).build())
                                .build(), "start_date", Field.Builder.of()
                                .withFactory("date")
                                .build(), "end_date", Field.Builder.of()
                                .withFactory("date")
                                .build(), "created_at", Field.Builder.of()
                                .withFactory("datetime")
                                .build(), "updated_at", Field.Builder.of().withFactory("datetime").build()))
                        .build(), "tasks", Repository.Builder.of()
                        .withFactory("jpa")
                        .withFields(Map.of("id", Field.Builder.of()
                                .withFactory("id")
                                .withPrimary(true)
                                .build(), "title", Field.Builder.of()
                                .withFactory("text")
                                .withRequired(true)
                                .withValidation(Validation.Builder.of().withMaxLength(255).build())
                                .build(), "description", Field.Builder.of()
                                .withFactory("textarea")
                                .withValidation(Validation.Builder.of().withMaxLength(1000).build())
                                .build(), "assigned_to", Field.Builder.of()
                                .withFactory("reference")
                                .withRepository("users")
                                .withField("id")
                                .withFilterField("username")
                                .withChildren(List.of("username"))
                                .build(), "status", Field.Builder.of()
                                .withFactory("select")
                                .withValues("task-status")
                                .build(), "due_date", Field.Builder.of()
                                .withFactory("date")
                                .withReadOnlyForRoles(List.of("developer"))
                                .build(), "created_at", Field.Builder.of()
                                .withFactory("datetime")
                                .build(), "updated_at", Field.Builder.of().withFactory("datetime").build()))
                        .build(), "task_has_task", Repository.Builder.of()
                        .withFactory("jpa")
                        .withFields(Map.of("task_id", Field.Builder.of()
                                .withFactory("id")
                                .build(), "related_task_id", Field.Builder.of().withFactory("id").build()))
                        .build(), "task_comments", Repository.Builder.of()
                        .withFactory("jpa")
                        .withFields(Map.of("id", Field.Builder.of()
                                .withFactory("id")
                                .withPrimary(true)
                                .build(), "comment_text", Field.Builder.of()
                                .withFactory("textarea")
                                .withValidation(Validation.Builder.of().withMaxLength(1000).build())
                                .build(), "user_id", Field.Builder.of()
                                .withFactory("number")
                                .build(), "created_at", Field.Builder.of()
                                .withFactory("datetime")
                                .withDefaultValue("now()")
                                .build()))
                        .build(), "images", Repository.Builder.of()
                        .withFactory("jpa")
                        .withFields(Map.of("id", Field.Builder.of()
                                .withFactory("id")
                                .withPrimary(true)
                                .build(), "title", Field.Builder.of()
                                .withFactory("text")
                                .withRequired(true)
                                .withValidation(Validation.Builder.of().withMaxLength(255).build())
                                .build(), "url", Field.Builder.of()
                                .withFactory("image")
                                .withRequired(true)
                                .withConfiguration(ImageFieldConfiguration.Builder.of().withFactory("default").build())
                                .build()))
                        .build()))
                .withForms(
                        Map.of("task", FormRoute.Builder.of()
                                .withRepository("tasks")
                                .withFactory("form")
                                .withConfiguration(FormConfiguration.Builder.of()
                                        .withTitleField("title")
                                        .withChildren(List.of(FormElement.Builder.of()
                                                .withField("title")
                                                .withType("field")
                                                .withLabel("route.tasks.labels.title")
                                                .build(), FormElement.Builder.of()
                                                .withField("description")
                                                .withType("field")
                                                .withLabel("route.tasks.labels.description")
                                                .build(), FormElement.Builder.of()
                                                .withField("status")
                                                .withType("field")
                                                .withLabel("route.tasks.labels.status")
                                                .build(), FormElement.Builder.of()
                                                .withField("due_date")
                                                .withType("field")
                                                .withLabel("route.tasks.labels.due_date")
                                                .build(), FormElement.Builder.of()
                                                .withField("assigned_to")
                                                .withType("field")
                                                .withLabel("route.tasks.labels.assigned_to")
                                                .build()))
                                        .build())
                                .build(), "project", FormRoute.Builder.of()
                                .withRepository("projects")
                                .withFactory("form")
                                .withTitle("route.projects.title-cards")
                                .withConfiguration(FormConfiguration.Builder.of()
                                        .withTitleField("name")
                                        .withChildren(List.of(FormElement.Builder.of()
                                                .withField("name")
                                                .withType("field")
                                                .withLabel("route.projects.labels.name")
                                                .build(), FormElement.Builder.of()
                                                .withField("description")
                                                .withType("field")
                                                .withLabel("route.projects.labels.description")
                                                .build(), FormElement.Builder.of()
                                                .withField("start_date")
                                                .withType("field")
                                                .withLabel("route.projects.labels.start_date")
                                                .build(), FormElement.Builder.of()
                                                .withField("end_date")
                                                .withType("field")
                                                .withLabel("route.projects.labels.end_date")
                                                .build()))
                                        .build())
                                .build(), "image", FormRoute.Builder.of()
                                .withRepository("images")
                                .withFactory("form")
                                .withTitle("route.images.title-cards")
                                .withConfiguration(FormConfiguration.Builder.of()
                                        .withTitleField("title")
                                        .withChildren(List.of(FormElement.Builder.of()
                                                .withField("title")
                                                .withType("field")
                                                .withLabel("route.images.labels.title")
                                                .build(), FormElement.Builder.of()
                                                .withField("url")
                                                .withType("field")
                                                .withLabel("route.images.labels.image")
                                                .build()))
                                        .build())
                                .build()))
                .withRoutes(Map.of("projects-cards", Route.Builder.of()
                        .withDefaultRoute(true)
                        .withFactory("grid")
                        .withRepository("projects")
                        .withIcon("FACTORY")
                        .withTitle("route.projects.title-cards")
                        .withConfiguration(RouteConfiguration.Builder.of()
                                .withFactory("card")
                                .withTitleField("name")
                                .withDescriptionField("description")
                                .build())
                        .withRoles(List.of("manager", "admin"))
                        .withChild(FormRoute.Builder.of().withRepository("projects").withFactory("form").build())
                        .build(), "images-grid", Route.Builder.of()
                        .withFactory("grid")
                        .withRepository("images")
                        .withIcon("CAMERA")
                        .withTitle("route.images.title-cards")
                        .withConfiguration(RouteConfiguration.Builder.of()
                                .withFactory("card")
                                .withTitleField("title")
                                .withImageField("url")
                                .withImageFactory("default")
                                .build())
                        .withRoles(List.of("manager", "admin"))
                        .withChild(FormRoute.Builder.of().withRepository("images").withFactory("form").build())
                        .build()))
                .build();

       /* if (config.isEmpty()) {
            throw new IllegalStateException("No TurboCRUD config found");
        }*/
    }

    public Application getConfiguration() {
        return configuration;
    }

    public Route getConfigForRoute(String viewName) {
        return configuration.getRoutes().get(viewName.split("/")[0]);
    }

    public String getApplicationName() {
        return configuration.getName();
    }
}
