# SQLite Datasource
spring.application.name=Project Management Platform Demo
spring.datasource.url=jdbc:sqlite:project-management-demo.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Liquibase
spring.liquibase.enabled=true